[advisories]
ignore = [
    # Ignore unmaintained `bincode`.
    # It is an optional dependency and is onlt implement traits from bincode.
    # See https://github.com/zheland/typed-index-collections/issues/10.
    "RUSTSEC-2025-0141",
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
]
confidence-threshold = 0.99
